### ISSUE TITLE
How to use trained model of custom dataset for inferencing? Error: AssertionError: ColorMode.IMAGE_BW requires segmentation.

### ISSUE THREAD

**Issue by init-22** [TannerGilbert/Detectron2-Train-a-Instance-Segmentation-Model#1]
Hello, 
I am new to Pytorch and Detectron so this might be a obvious or easy question but I am unable to understand some logic behind the script I have.

** have trained a model using the following code:**
register_coco_instances("train_500", {}, "/home/ubuntu/Documents/isaac/detectron2/MRCCN_training/500_coco_label.json", "/home/ubuntu/Documents/isaac/detectron2/MRCCN")

metadata = MetadataCatalog.get("train_500")
dataset_dicts = DatasetCatalog.get("train_500")

cfg = get_cfg()
cfg.merge_from_file("/home/ubuntu/Documents/isaac/detectron2/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")
cfg.DATASETS.TRAIN = ("train_500",)
cfg.DATASETS.TEST = ()   # no metrics implemented for this dataset
cfg.DATALOADER.NUM_WORKERS = 2
cfg.MODEL.WEIGHTS = "detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl"  # initialize from model zoo
cfg.SOLVER.IMS_PER_BATCH = 2
cfg.SOLVER.BASE_LR = 0.02
cfg.SOLVER.MAX_ITER = 1000   # 300 iterations seems good enough, but you can certainly train longer
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 128   # faster, and good enough for this toy dataset
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 3  # 3 classes (data, fig, hazelnut)

cfg.OUTPUT_DIR = '/home/ubuntu/Documents/isaac/detectron2/train_output/'

os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
trainer = DefaultTrainer(cfg)
trainer.resume_or_load(resume=False)
trainer.train()

**Then I am using this script for inferencing:**

cfg = get_cfg()

cfg.OUTPUT_DIR = '/home/ubuntu/Documents/isaac/detectron2/train_output/'

cfg.MODEL.WEIGHTS = os.path.join(cfg.OUTPUT_DIR, "model_final.pth")
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5   # set the testing threshold for this model
cfg.DATASETS.TEST = ("train_500", )
predictor = DefaultPredictor(cfg)

metadata = MetadataCatalog.get("train_500")

from detectron2.utils.visualizer import ColorMode
path = '/home/ubuntu/Documents/isaac/detectron2/MRCCN/50-45.jpg'
im = cv2.imread(path)
outputs = predictor(im)

v = Visualizer(im[:, :, ::-1],
                   metadata=metadata, 
                   scale=0.5,
                   instance_mode=ColorMode.IMAGE_BW   # remove the colors of unsegmented pixels
    )
v = v.draw_instance_predictions(outputs["instances"].to("cpu"))
cv2.imwrite("test_image.jpg", v.get_image()[:, :, ::-1])

**This is the error I am getting**

'proposal_generator.anchor_generator.cell_anchors.0' has shape (3, 4) in the checkpoint but (15, 4) in the model! Skipped.
'proposal_generator.rpn_head.conv.weight' has shape (256, 256, 3, 3) in the checkpoint but (1024, 1024, 3, 3) in the model! Skipped.
'proposal_generator.rpn_head.conv.bias' has shape (256,) in the checkpoint but (1024,) in the model! Skipped.
'proposal_generator.rpn_head.objectness_logits.weight' has shape (3, 256, 1, 1) in the checkpoint but (15, 1024, 1, 1) in the model! Skipped.
'proposal_generator.rpn_head.objectness_logits.bias' has shape (3,) in the checkpoint but (15,) in the model! Skipped.
'proposal_generator.rpn_head.anchor_deltas.weight' has shape (12, 256, 1, 1) in the checkpoint but (60, 1024, 1, 1) in the model! Skipped.
'proposal_generator.rpn_head.anchor_deltas.bias' has shape (12,) in the checkpoint but (60,) in the model! Skipped.
'roi_heads.box_predictor.cls_score.weight' has shape (4, 1024) in the checkpoint but (81, 2048) in the model! Skipped.
'roi_heads.box_predictor.cls_score.bias' has shape (4,) in the checkpoint but (81,) in the model! Skipped.
'roi_heads.box_predictor.bbox_pred.weight' has shape (12, 1024) in the checkpoint but (320, 2048) in the model! Skipped.
'roi_heads.box_predictor.bbox_pred.bias' has shape (12,) in the checkpoint but (320,) in the model! Skipped.
Traceback (most recent call last):
  File "inference_mrcnn.py", line 52, in <module>
    v = v.draw_instance_predictions(outputs["instances"].to("cpu"))
  File "/home/ubuntu/Documents/isaac/detectron2/detectron2/utils/visualizer.py", line 364, in draw_instance_predictions
    assert predictions.has("pred_masks"), "ColorMode.IMAGE_BW requires segmentations"
AssertionError: ColorMode.IMAGE_BW requires segmentations

Also, I realise that the model is using huge chunk of memory while inferencing which is not optimal, Where am I messing things up?

**Comment by TannerGilbert** [comment]
Normally using ColorMode.IMAGE_BW should work with a Mask R-CNN, but nonetheless I'd try removing the line ```instance_mode=ColorMode.IMAGE_BW # remove the colors of unsegmented pixels``` and see if it works. 

Related issue:
- https://github.com/facebookresearch/detectron2/issues/434

**Comment by init-22** [comment]
@TannerGilbert Thank you so much for your response, adding the following lines again in my inference code solved the problem.

from detectron2.data.datasets import register_coco_instances
register_coco_instances("train_500", {}, "/home/ubuntu/Documents/isaac/detectron2/MRCCN_training/500_coco_label.json", "/home/ubuntu/Documents/isaac/detectron2/MRCCN_training")

metadata = MetadataCatalog.get("train_500")
dataset_dicts = DatasetCatalog.get("train_500")


also, 
cfg.merge_from_file("/home/ubuntu/Documents/isaac/detectron2/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"),
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 3



Thanks :)

**Comment by TannerGilbert** [comment]
Nice to hear. Will close the issue now.
