### ISSUE TITLE
CUDA error: device-side assert triggered need solution 

### ISSUE THREAD

**Issue by ShakhayatHossainShykat** [TannerGilbert/Detectron2-Train-a-Instance-Segmentation-Model#10]
When i tried to run this portion this error shows. I need a solution to fix this problem. @TannerGilbert please help
![Screenshot (84)](https://user-images.githubusercontent.com/44720412/128834630-72abaa18-c43b-4dad-8bfb-5f0d1d4e93c2.png)
![Screenshot (85)](https://user-images.githubusercontent.com/44720412/128834626-9c776af3-7bfe-4c27-9cce-a226fbd36b61.png)

**Comment by TannerGilbert** [comment]
I'm not sure what causes this issue, but I have just updated all the notebooks to the newest Detectron2 version. So maybe try it out again and see if it works now.

**Comment by ShakhayatHossainShykat** [comment]
Is there any way to resume training from checkpoints manually?
Because of network interruption  training stops then I have to train it again from the beginning.

**Comment by TannerGilbert** [comment]
If you still have the checkpoints, you can continue training by changing the path to the pretrained weights (`cfg.MODEL.WEIGHTS`) and by setting `resume=True` when calling `trainer.resume_or_load`. For an example, take a look at [one of my other notebooks](https://colab.research.google.com/github/TannerGilbert/Object-Detection-and-Image-Segmentation-with-Detectron2/blob/master/Detectron2_train_on_a_custom_dataset.ipynb#scrollTo=mp8JaQ73wvjD).

**Comment by ShakhayatHossainShykat** [comment]
@TannerGilbert  Thank you for your reply!
I was Trying the resume part. I was facing error in this part
![Screenshot (154)](https://user-images.githubusercontent.com/44720412/133458976-a541f582-f4bb-4b09-8cb0-af21c794534d.png)
![Screenshot (155)](https://user-images.githubusercontent.com/44720412/133459181-943fabc6-3332-402b-99e8-3f26eff3da95.png)

**Comment by ShakhayatHossainShykat** [comment]
Is there any way to get .pkl file ?

**Comment by TannerGilbert** [comment]
> @TannerGilbert Thank you for your reply! I was Trying the resume part. I was facing error in this part ![Screenshot (154)](https://user-images.githubusercontent.com/44720412/133458976-a541f582-f4bb-4b09-8cb0-af21c794534d.png) ![Screenshot (155)](https://user-images.githubusercontent.com/44720412/133459181-943fabc6-3332-402b-99e8-3f26eff3da95.png)

You need to change the training dataset again `cfg.DATASETS.TRAIN =(DTA_train,)`
