### ISSUE TITLE
how to visualizer this instance segmentation just with one colour ?

### ISSUE THREAD

**Issue by Adithia99** [TannerGilbert/Detectron2-Train-a-Instance-Segmentation-Model#3]
how to visualizer this instance segmentation just with one colour ?
for ex : car always blue,person always  red etc

so just in one colour

**Comment by TannerGilbert** [comment]
Use the thing ```thing_colors```parameter as described in the documentation:
https://detectron2.readthedocs.io/tutorials/datasets.html#metadata-for-datasets
https://detectron2.readthedocs.io/modules/utils.html#detectron2.utils.visualizer.ColorMode

**Comment by Adithia99** [comment]
import random
from detectron2.data import DatasetCatalog, MetadataCatalog

dataset_dicts = DatasetCatalog.get("customnew_train")
microcontroller_metadata = MetadataCatalog.get("customnew_train").thing_colors 

for d in random.sample(dataset_dicts, 31):
    img = cv2.imread(d["file_name"])
    v = Visualizer(img[:, :, ::-1], metadata=microcontroller_metadata, scale=1)
    v = v.draw_dataset_dict(d)
    plt.figure(figsize = (14, 10))
    plt.imshow(cv2.cvtColor(v.get_image()[:, :, ::-1], cv2.COLOR_BGR2RGB))
    plt.show()



get error like this
WARNING [07/30 18:51:34 d2.data.datasets.coco]: 
Category ids in annotations are not in [1, #categories]! We'll apply a mapping for you.

[07/30 18:51:34 d2.data.datasets.coco]: Loaded 142 images in COCO format from custom/train.json
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-29-79bd9c29e369> in <module>()
      8     img = cv2.imread(d["file_name"])
      9     v = Visualizer(img[:, :, ::-1], metadata=microcontroller_metadata, scale=1)
---> 10     v = v.draw_dataset_dict(d)
     11     plt.figure(figsize = (14, 10))
     12     plt.imshow(cv2.cvtColor(v.get_image()[:, :, ::-1], cv2.COLOR_BGR2RGB))

/usr/local/lib/python3.6/dist-packages/detectron2/utils/visualizer.py in draw_dataset_dict(self, dic)
    528                     self._jitter([x / 255 for x in self.metadata.thing_colors[c]]) for c in labels
    529                 ]
--> 530             names = self.metadata.get("thing_classes", None)
    531             if names:
    532                 labels = [names[i] for i in labels]

AttributeError: 'list' object has no attribute 'get'

**Comment by Adithia99** [comment]
thank you but i got some error maybe u can fix it :)


import random
from detectron2.data import DatasetCatalog, MetadataCatalog

dataset_dicts = DatasetCatalog.get("customnew_train")
microcontroller = MetadataCatalog.get("customnew_train").set(thing_colors =(list[tuple(r, g, b)]))    ## 

for d in random.sample(dataset_dicts, 2):
    img = cv2.imread(d["file_name"])
    v = Visualizer(img[:, :, ::-1], metadata=microcontroller, scale=1)
    v = v.draw_dataset_dict(d)
    plt.figure(figsize = (14, 10))
    plt.imshow(cv2.cvtColor(v.get_image()[:, :, ::-1], cv2.COLOR_BGR2RGB))
    plt.show()


can u help me about this "(list[tuple(r, g, b)]))" mean and make it to example i use your codes so it gonna be easy for you ? 
i dont know what i must fill it , i was tried but got many error haha

**Comment by TannerGilbert** [comment]
It should look something like:

```python
MetadataCatalog.get("my_dataset").thing_colors = [(255,0,0), (0,255,0)]
```

For more information you can also check out: https://github.com/facebookresearch/detectron2/issues/655

**Comment by Adithia99** [comment]
same sir , still cant get same error using MetadataCatalog.get("my_dataset").thing_colors = [(255,0,0), (0,255,0)]

AssertionError: Attribute 'thing_colors' in the metadata of 'customnew_train' cannot be set to a different value!
[] != [(255, 0, 0), (0, 255, 0)]

and the author detectron direct to read that, i was but still dont understand what i must do, help me :)

Answered in docs https://detectron2.readthedocs.io/modules/utils.html#detectron2.utils.visualizer.ColorMode

**Comment by Adithia99** [comment]
i mean how to use that how to call
detectron2.utils.visualizer.ColorMode(value)
segmentation = 1
thanks

**Comment by Adithia99** [comment]
got error sir if like that so i used method number 2, but still got error little error

import random
from detectron2.data import DatasetCatalog, MetadataCatalog
from detectron2.utils.visualizer import Visualizer
from detectron2.utils.visualizer import ColorMode(1)
ColorMode(1)

dataset_dicts = DatasetCatalog.get("customnew_train")
microcontroller_metadata = MetadataCatalog.get("customnew_train")

for d in random.sample(dataset_dicts, 2):
    img = cv2.imread(d["file_name"])
    v = Visualizer(img[:, :, ::-1], metadata=microcontroller_metadata, scale=1,instance_mode=ColorMode.SEGMENTATION)
    v = v.draw_dataset_dict(d)
    plt.figure(figsize = (14, 10))
    plt.imshow(cv2.cvtColor(v.get_image()[:, :, ::-1], cv2.COLOR_BGR2RGB))
    plt.show()

which one line i must change? 
i change that instance_colour to segmentation = 2 based on author facebook research but still got random colour

**Comment by TannerGilbert** [comment]
You need to set:

```python
MetadataCatalog.get("<data-set name>").set(thing_colors=[(255, 0, 0)])
```

and then set instace_mode to segmentation when visualizing the images:

```python
from detectron2.utils.visualizer import ColorMode
dataset_dicts = get_balloon_dicts("<dataset>")
for d in random.sample(dataset_dicts, 3):    
    im = cv2.imread(d["file_name"])
    outputs = predictor(im)
    v = Visualizer(im[:, :, ::-1],
                   metadata=balloon_metadata, 
                   scale=0.8, 
                   instance_mode=ColorMode.SEGMENTATION
    )
    v = v.draw_instance_predictions(outputs["instances"].to("cpu"))
    plt.figure(figsize = (14, 10))
    plt.imshow(cv2.cvtColor(v.get_image()[:, :, ::-1], cv2.COLOR_BGR2RGB))
    plt.show()
```

**Comment by Adithia99** [comment]
thank you gilbert , very usefull

**Comment by AbhishekMaity001** [comment]
@TannerGilbert  can you please look into this [link](https://github.com/facebookresearch/detectron2/issues/2775#issue-836908175)
This feature needs to be added ....till then please suggest some alternative if possible. Please have a look into this
