### ISSUE TITLE
Adding in augmentations for custom dataset

### ISSUE THREAD

**Issue by marvision-ai** [TannerGilbert/Detectron2-Train-a-Instance-Segmentation-Model#4]
@TannerGilbert  Thank you for the great repo! 

I see in an earlier tutorial you have showed how to use augmentations with a dataset: https://gilberttanner.com/blog/detectron-2-object-detection-with-pytorch

Could you add this augmentation workflow to the google collab when using your own custom dataset? 

Thank you!

**Comment by TannerGilbert** [comment]
I already added it to my [Microcontroller detection notebook](https://github.com/TannerGilbert/Microcontroller-Detection-with-Detectron2/blob/master/Detectron2_Detect_Microcontrollers_with_data_augmentation.ipynb). I'll also try to add it to the other repos the upcoming days

**Comment by TannerGilbert** [comment]
I also added an [example](https://github.com/TannerGilbert/Object-Detection-and-Image-Segmentation-with-Detectron2/blob/master/Detectron2_Train_on_a_custom_dataset_with_data_augmentation.ipynb) to the [Object-Detection-and-Image-Segmentation-with-Detectron2 repo](https://github.com/TannerGilbert/Object-Detection-and-Image-Segmentation-with-Detectron2).

I'll close this issue. If you have any further questions feel free to reopen it.

**Comment by marvision-ai** [comment]
@TannerGilbert awesome! Looks great. Thanks for your hard work. 

I have another question but I will leave it to a different issue.
