### ISSUE TITLE
How to register my own dataset in caffe2_converter.py?

### ISSUE THREAD

**Issue by x12901** [TannerGilbert/Detectron2-Train-a-Instance-Segmentation-Model#5]
Great project and I can successfully train using my dataset. I would like to convert the model to run in other environments. I tried to modify caffe2_converter.py, but it doesn't seem to work. Do you have any ideas on how to do this?
https://github.com/facebookresearch/detectron2/blob/master/tools/deploy/caffe2_converter.py

**Comment by TannerGilbert** [comment]
I'll try to create an example notebook for this the upcoming days

**Comment by TannerGilbert** [comment]
I successfully converted the model to caffe2, onnx, and torchvision using the caffe2.converter.py file. You can check it out [here](https://github.com/TannerGilbert/Object-Detection-and-Image-Segmentation-with-Detectron2/blob/master/Detectron2_train_and_export_model.ipynb)
