### ISSUE TITLE
No detection while reloading the model in a new python file after training on custom dataset

### ISSUE THREAD

**Issue by karankatiyar92** [TannerGilbert/Detectron2-Train-a-Instance-Segmentation-Model#7]
hi , i went through your repo , trained a model  but i got stuck with an issue . 

i have trained an instance segmentation model using mask_rcnn-50 layers config model on my custom dataset and after training i tried to test the model . here are my two scenarios:

when i train and test the model in same jupyter notebook it works fine .

but when i train on seperate notebook and test on seperate jupyter ntbk or a new python file by loading the model.pth file and giving the same config(yaml) file while training , it wont detect anything on the same data i tested on the first case . please let me know why is that happening . i am using the below code for testing

###import all libraries
from detectron2.utils.visualizer import ColorMode

cfg = get_cfg()
cfg.merge_from_file(model_zoo.get_config_file("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"))
cfg.MODEL.WEIGHTS = os.path.join(cfg.OUTPUT_DIR, "model_final.pth") #the model that i got after training
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5

predictor = DefaultPredictor(cfg)

dataset_dicts = get_microcontroller_dicts('Microcontroller Segmentation/test')
for d in random.sample(dataset_dicts, 3):
im = cv2.imread(d["file_name"])
outputs = predictor(im)
v = Visualizer(im[:, :, ::-1],
metadata=microcontroller_metadata,
scale=0.8,
instance_mode=ColorMode.IMAGE_BW # remove the colors of unsegmented pixels
)
v = v.draw_instance_predictions(outputs["instances"].to("cpu"))
plt.figure(figsize = (14, 10))
plt.imshow(cv2.cvtColor(v.get_image()[:, :, ::-1], cv2.COLOR_BGR2RGB))
plt.show()

Thanks

**Comment by TannerGilbert** [comment]
If you want to use your model in another environment make sure to download the model and config.

I added an example on how to save the config and use it to load back the model in the [Detectron2_train_on_a_custom_dataset.ipynb notebook](https://github.com/TannerGilbert/Object-Detection-and-Image-Segmentation-with-Detectron2/blob/master/Detectron2_train_on_a_custom_dataset.ipynb)
