### ISSUE TITLE
Why do we need to resize the image for training

### ISSUE THREAD

**Issue by berkantay** [TannerGilbert/Detectron2-Train-a-Instance-Segmentation-Model#8]
Why we resize the image to 800x600 I cannot see any configuration for input image size at config part of the code.

Best Regards

**Comment by TannerGilbert** [comment]
Actually you don't need to resize your images. You only need to specify the width and height when registering the data-set.

**Comment by berkantay** [comment]
Oh I get it, but it does mean that input image size should be fixed

**Comment by TannerGilbert** [comment]
No the input size doesn't have to be fixed. I just have 800x600 because I created that data-set for another project where I used another framework which required a fixed size.

**Comment by berkantay** [comment]
Now I understand thank you Gilbert

**Comment by TannerGilbert** [comment]
Good to hear. I'll close this issue now. If you have any further questions feel free to ask.

**Comment by berkantay** [comment]
Hello Gilbert,

Actually I need advice for my project? I do not know if this mail was sent
directly to your personal mail or not? If not could you please share your
personal mail?

Best Regards

Tanner Gilbert <notifications@github.com>, 20 Eki 2020 Sal, 17:47 tarihinde
şunu yazdı:
